line-length = 100

[lint]
select = ["D", "E", "W", "F", "C901", "I"] # D (docstring errors), E (PEP 8 errors), W (warning codes), F (pyflakes codes), C901 ('if' block is too complex), I (import errors)
ignore = ["D203", "D213", "D407"] # Ignore incompatible rules, D407 (Missing dashed underline after section)
