# Config file version = 0.1.0
line-length = 100
target-version = "py38"

[lint]
select = ["ALL"]
ignore = [
    #### Modules
    "PT", # https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt. Using nose2 instead of pytest.
    "FBT", # https://docs.astral.sh/ruff/rules/#flake8-boolean-trap-fbt.
    "EM", # https://docs.astral.sh/ruff/rules/#flake8-errmsg-em.

    #### Specific rules
    "D203", # https://docs.astral.sh/ruff/rules/#pydocstyle-d. Incompatible with D211.
    "D212", # https://docs.astral.sh/ruff/rules/#pydocstyle-d. Incompatible with D213.
    "D407", # https://docs.astral.sh/ruff/rules/#pydocstyle-d. Makes docstrings less readable.
    "TD002", "FIX002", # https://docs.astral.sh/ruff/rules/#flake8-todos-td. TD003 is sufficient.
    "COM812", # https://docs.astral.sh/ruff/rules/#flake8-commas-com. Trailing comma, makes code less readable in some cases? for now keep disabled
    "TRY003", # https://docs.astral.sh/ruff/rules/#tryceratops-try.
    "LOG015", # Allow calling default logger
]

[lint.per-file-ignores]
"tests/*" = [
    "S106", # hardcoded passwords
]

[lint.pylint]
max-args = 10

[lint.flake8-annotations]
suppress-none-returning = true # Allow returning none, if nothing is returned

[format]
line-ending = "lf"
