line-length = 100
target-version = "py312"

[lint]
select = ["ALL"]
ignore = [
    #### Modules
    "PT", # https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt. Using nose2 instead of pytest.
    "FBT", # https://docs.astral.sh/ruff/rules/#flake8-boolean-trap-fbt. Makes code more complex and less readable.
    "PTH", # https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth. Normal method is fine.
    "EM", # https://docs.astral.sh/ruff/rules/#flake8-errmsg-em . This is fine...

    #### Specific rules
    "D203", # incompatible with D211
    "D212", # incompatible with D213
    "D407", # https://docs.astral.sh/ruff/rules/#pydocstyle-d
    "TD002", # https://docs.astral.sh/ruff/rules/#flake8-todos-td. TD003 is sufficient
    "COM812", # https://docs.astral.sh/ruff/rules/#flake8-commas-com. Trailing comma, makes code less readable in some cases.
    "TRY003", # https://docs.astral.sh/ruff/rules/#tryceratops-try. This is fine...
]

[lint.pylint]
max-args = 10

[lint.flake8-annotations]
suppress-none-returning = true # Allow returning none, if nothing is returned

[format]
line-ending = "lf"
