line-length = 100
target-version = "py312"

[lint] # TODO: look at ruff rules (added select all for more complete code formatting, but also needs more ignores...)
select = ["ALL"]
ignore = [
    #### Modules
    "PT", # https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt. Using nose2 instead of pytest.
    "FBT", # https://docs.astral.sh/ruff/rules/#flake8-boolean-trap-fbt. Makes code more complex and less readable?
    "PTH", # https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth. Normal method is fine?
    "EM", # https://docs.astral.sh/ruff/rules/#flake8-errmsg-em . This is fine?

    #### Specific rules
    "D203", # https://docs.astral.sh/ruff/rules/#pydocstyle-d incompatible with D211.
    "D212", # Incompatible with D213.
    "D407", # Makes docstrings less readable.
    "TD002", # https://docs.astral.sh/ruff/rules/#flake8-todos-td. TD003 is sufficient.
    # "COM812", # https://docs.astral.sh/ruff/rules/#flake8-commas-com. Trailing comma, makes code less readable in some cases?
    "TRY003", # https://docs.astral.sh/ruff/rules/#tryceratops-try. This is fine?
    "TRY301", # https://docs.astral.sh/ruff/rules/#tryceratops-try. This is fine?
]

[lint.per-file-ignores]
"tests/*" = [
    "S106", # hardcoded passwords
    "D", # Docstrings
]

[lint.pylint]
max-args = 10

[lint.flake8-annotations]
suppress-none-returning = true # Allow returning none, if nothing is returned

[format]
line-ending = "lf"
