name: Build Sphinx docs

on:
  push:
    branches:
      - main

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Start time
        uses: shinto-labs/send-log-to-loki@v1.0.4
        with:
          measurement: start

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.12"

      - name: Install safe-chain
        run: |
          curl -fsSL https://github.com/AikidoSec/safe-chain/releases/latest/download/install-safe-chain.sh | sh -s -- --ci
          export PATH="$HOME/.safe-chain/shims:$HOME/.safe-chain/bin:${PATH}"
          pip safe-chain-verify

      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_READ_ALL_INTERNAL_REPOS }}
          SAFE_CHAIN_LOGGING: verbose
        run: |
          git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "ssh://git@github.com/"
          pdm export -f requirements --dev --no-hashes -o requirements.txt
          pip install --no-cache-dir -r requirements.txt

      - name: Generate docs
        run: sphinx-apidoc -f -o docs/modules shinto && cd docs && make html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_build/html

  deploy:
    needs: build_docs
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  send_to_loki:
    runs-on: ubuntu-latest
    if: always()
    needs: [build_docs, deploy]

    steps:
      - name: Send Logs to Loki
        uses: shinto-labs/send-log-to-loki@v1.0.4
        with:
          loki_address: "https://loki.shintolabs.net"
          loki_username: ${{ secrets.LOKI_USERNAME }}
          loki_password: ${{ secrets.LOKI_PASSWORD }}
          status: ${{ job.status }}
