name: Ruff format check

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:
    branches:
      - "**"

jobs:
  ruff-format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Start time
        id: start_time
        run: echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruff
        run: pip install ruff

      - name: Check code format
        id: ruff
        run: |
          ruff_output=$(ruff check . || true)
          echo "$ruff_output"

          errors=$(echo "$ruff_output" | grep "Found .* errors" | grep -oP "\d+")

          if [[ -n $errors && $errors -gt 0 ]]; then
            echo "errors=$errors" >> $GITHUB_OUTPUT
          else
            echo "errors=0" >> $GITHUB_OUTPUT
          fi

      - name: Send results to Loki
        if: always()
        env:
          LOKI_ADDRESS: "https://loki.shintolabs.net"
          LOKI_USERNAME: ${{ secrets.LOKI_USERNAME }}
          LOKI_PASSWORD: ${{ secrets.LOKI_PASSWORD }}
          REPOSITORY: ${{ github.repository }}
          WORKFLOW: ${{ github.workflow }}
          JOB: ${{ github.job }}
          STATUS: ${{ job.status }}
          RUN_ID: ${{ github.run_id }}
          RUN_NUMBER: ${{ github.run_number }}
          ACTOR: ${{ github.actor }}
          URL: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
          REF: ${{ github.ref }}
          START_TIME: ${{ steps.start_time.outputs.start_time }}
          VALUES: 'ruff_errors="${{ steps.ruff.outputs.errors }}"'
        run: |
          ./scripts/send_to_loki.sh
