# file_version = "0.1.1"
name: Ruff format check

on:
  push:
    branches:
      - main
      - development
    paths:
      - "**/*.py"
      - ".github/workflows/ruff_format.yml"
      - "scripts/send_to_loki.sh"
      - "ruff.toml"
  pull_request:
    branches:
      - "**"
    paths:
      - "*.py"
      - ".github/workflows/ruff_format.yml"
      - "scripts/send_to_loki.sh"
      - "ruff.toml"

jobs:
  ruff-format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Start time
        uses: shinto-labs/send-log-to-loki@v1.0.3
        with:
          measurement: start

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Check code format
        id: ruff
        run: |
          set +e
          ruff_output=$(ruff check . 2>&1)
          exit_code=$?
          set -e
          echo "$ruff_output"

          errors=$(echo "$ruff_output" | grep "Found [0-9]\+ errors" | grep -oE "[0-9]+" || echo 0)

          echo "errors=$errors" >> $GITHUB_OUTPUT

          exit "$exit_code"

      - name: Send Logs to Loki
        if: always()
        uses: shinto-labs/send-log-to-loki@v1.0.3
        with:
          loki_address: "https://loki.shintolabs.net"
          loki_username: ${{ secrets.LOKI_USERNAME }}
          loki_password: ${{ secrets.LOKI_PASSWORD }}
          status: ${{ job.status }}
          additional_labels: "ruff_errors=${{ steps.ruff.outputs.errors }}"
